baseURL = 'https://example.org/'
locale = 'en-us'
defaultContentLanguage = 'en-us'
title = 'tekst'

[module]
[module.hugoVersion]
extended = false
min = "0.160.0"

# Default config
[markup]
[markup.highlight]
noClasses = false

[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

[params.json-ld]
posts = { page = "blog-posting", section = "collection-page" }
publications = { page = "scholarly-article", section = "collection-page" }
