baseURL = 'https://example.org/'
locale = 'en-us'
defaultContentLanguage = 'en-us'
title = 'tekst'

[module]
[module.hugoVersion]
extended = false
min = "0.160.0"

# Default config
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

[markup]
[markup.highlight]
noClasses = false
