name = 'Tekst'
license = 'MIT'
licenselink = 'https://github.com/crnh/tekst/blob/main/LICENSE'
description = 'A simple Hugo theme'

homepage = 'https://github.com/crnh/tekst'

tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
  "minimal",
  "personal",
  "portfolio",
]

features = [
  "responsive",
  "blog",
  "table-of-contents",
  "highlight.js",
  "favicon",
  "social-icons",
  "minified-assets",
  "dark-light-images",
  "color-palettes",
]

[author]
name = 'Corné Haasjes'
